# Generated by Django 4.1.7 on 2023-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='catering',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='local_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='post_code_first',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='post_code_second',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='private_parking',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sound_system',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='street',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='room',
            name='street_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='tables',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='room',
            name='projector',
            field=models.BooleanField(default=None),
        ),
    ]
